add_lunch_combo codenamedroid_crespo-userdebug
add_lunch_combo codenamedroid_crespo4g-userdebug
add_lunch_combo codenamedroid_maguro-userdebug
add_lunch_combo codenamedroid_toro-userdebug
add_lunch_combo codenamedroid_stingray-userdebug
add_lunch_combo codenamedroid_wingray-userdebug

